-- TITLE1:Apply List
-- TITLE2:Display Apply information
-- DESC:
SELECT 
 APPLY_USER,
 APPLY_NAME,
 QUEUE_NAME,
 APPLY_CAPTURED,
 RULE_SET_NAME,
 APPLY_DATABASE_LINK,
 APPLY_TAG,
 STATUS
FROM DBA_APPLY
ORDER BY APPLY_NAME;
