-- TITLE1:
-- TITLE2: Displaying the DDL Handler for Each Apply Process
-- DESC:

COLUMN APPLY_NAME HEADING 'Apply Process Name' FORMAT A20
COLUMN DDL_HANDLER HEADING 'DDL Handler' FORMAT A40

SELECT APPLY_NAME, DDL_HANDLER FROM DBA_APPLY WHERE DDL_HANDLER IS NOT NULL;
