--
-- p1.sql
--

Prompt Make process definition

INSERT INTO WF_PROCESSES ( ID, NAME, DESCRIPTION, CREATION_DATE, VERSION, AUTHOR, DURATION, LIMIT,
VALID_FROM, VALID_TO, WAITING_TIME, WORKING_TIME, REPLICATION_TIMESTAMP ) VALUES ( 
10, 'FILE BONUS REQUEST', 'The process of filing a request for a bonus by an employee.'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
/

Prompt Add activities

INSERT INTO WF_ACTIVITIES ( PRCE_ID, ID, PRCE_ID_HAS_SUBFLOW, PATI_query, APLI_ID, NAME, DESCRIPTION,
JOIN, SPLIT, create_delay_expr, WORKLIST_DISPLAY_QUERY, START_MODE, FINISH_MODE, IMPLEMENTATION,
SUBFLOW_EXECUTION, LIMIT, PRIORITY, REPLICATION_TIMESTAMP ) VALUES ( 
10, 10, NULL, 10, NULL, 'File request to manager', 'File request to manager', NULL
, NULL, NULL, NULL, 'MANUAL', 'MANUAL', 'NO', NULL, NULL, NULL, NULL)
/
INSERT INTO WF_ACTIVITIES ( PRCE_ID, ID, PRCE_ID_HAS_SUBFLOW, pati_query, APLI_ID, NAME, DESCRIPTION,
JOIN, SPLIT, create_delay_expr, WORKLIST_DISPLAY_QUERY, START_MODE, FINISH_MODE, IMPLEMENTATION,
SUBFLOW_EXECUTION, LIMIT, PRIORITY, REPLICATION_TIMESTAMP ) VALUES ( 
10, 20, NULL, 20, NULL, 'Decide on bonus request', 'Decide on bonus request', NULL
, 'XOR', NULL, NULL, 'MANUAL', 'MANUAL', 'NO', NULL, NULL, NULL, NULL)
/
INSERT INTO WF_ACTIVITIES ( PRCE_ID, ID, PRCE_ID_HAS_SUBFLOW, pati_query, APLI_ID, NAME, DESCRIPTION,
JOIN, SPLIT, create_delay_expr, WORKLIST_DISPLAY_QUERY, START_MODE, FINISH_MODE, IMPLEMENTATION,
SUBFLOW_EXECUTION, LIMIT, PRIORITY, ASSIGN_TO, REPLICATION_TIMESTAMP ) VALUES ( 
10, 30, NULL, 10, NULL, 'Read bonus request denial', 'Read bonus request denial', NULL
, 'XOR', NULL, NULL, 'MANUAL', 'MANUAL', 'NO', NULL, NULL, NULL,
'select pati_id
 from wf_performers
 where state = ''CURRENT''
   and acin_id =
 (select id
   from  wf_activity_instances
  where acti_prce_id=10
    and acti_id=10
    and prin_id = :prin_id_in)
', NULL)
/
INSERT INTO WF_ACTIVITIES ( PRCE_ID, ID, PRCE_ID_HAS_SUBFLOW, pati_query, APLI_ID, NAME, DESCRIPTION,
JOIN, SPLIT, create_delay_expr, WORKLIST_DISPLAY_QUERY, START_MODE, FINISH_MODE, IMPLEMENTATION,
SUBFLOW_EXECUTION, LIMIT, PRIORITY, ASSIGN_TO, REPLICATION_TIMESTAMP ) VALUES ( 
10, 40, NULL, 10, NULL, 'File bonus request to president', 'File bonus request to president'
, NULL, NULL, NULL, NULL, 'MANUAL', 'MANUAL', 'NO', NULL, NULL, NULL, 
'select pati_id
 from wf_performers
 where state = ''CURRENT''
   and acin_id =
 (select id
   from  wf_activity_instances
  where acti_prce_id=10
    and acti_id=10
    and prin_id = :prin_id_in)
', NULL)
/
INSERT INTO WF_ACTIVITIES ( PRCE_ID, ID, PRCE_ID_HAS_SUBFLOW, pati_query, APLI_ID, NAME, DESCRIPTION,
JOIN, SPLIT, create_delay_expr, WORKLIST_DISPLAY_QUERY, START_MODE, FINISH_MODE, IMPLEMENTATION,
SUBFLOW_EXECUTION, LIMIT, PRIORITY, REPLICATION_TIMESTAMP ) VALUES ( 
10, 50, NULL, 7839, NULL, 'Final decision on bonus request', 'Final decision on bonus request'
, 'XOR', 'AND', NULL, NULL, 'MANUAL', 'MANUAL', 'NO', NULL, NULL, NULL, NULL)
/
INSERT INTO WF_ACTIVITIES ( PRCE_ID, ID, PRCE_ID_HAS_SUBFLOW, pati_query, APLI_ID, NAME, DESCRIPTION,
JOIN, SPLIT, create_delay_expr, WORKLIST_DISPLAY_QUERY, START_MODE, FINISH_MODE, IMPLEMENTATION,
SUBFLOW_EXECUTION, LIMIT, PRIORITY, ASSIGN_TO, REPLICATION_TIMESTAMP ) VALUES ( 
10, 60, NULL, 10, NULL, 'Read request result', 'Read request result', NULL, NULL, NULL
, NULL, 'MANUAL', 'MANUAL', 'NO', NULL, NULL, NULL, 
'select pati_id
 from wf_performers
 where state = ''CURRENT''
   and acin_id =
 (select id
   from  wf_activity_instances
  where acti_prce_id=10
    and acti_id=10
    and prin_id = :prin_id_in)
', NULL)
/
INSERT INTO WF_ACTIVITIES ( PRCE_ID, ID, PRCE_ID_HAS_SUBFLOW, pati_query, APLI_ID, NAME, DESCRIPTION,
JOIN, SPLIT, create_delay_expr, WORKLIST_DISPLAY_QUERY, START_MODE, FINISH_MODE, IMPLEMENTATION,
SUBFLOW_EXECUTION, LIMIT, PRIORITY, REPLICATION_TIMESTAMP ) VALUES ( 
10, 70, NULL, 40, NULL, 'Add bonus to paycheck', 'Add bonus to paycheck', NULL, NULL
, NULL, NULL, 'MANUAL', 'MANUAL', 'NO', NULL, NULL, NULL, NULL)
/

Prompt Add attributes

INSERT INTO WF_ATTRIBUTES ( ID, PRCE_ID, DATA_TYPE, NAME, LENGTH, DESCRIPTION, INITIAL_VALUE, KEEP,
REPLICATION_TIMESTAMP ) VALUES ( 
10, 10, 'INTEGER', 'EMPNO', 10, 'Link to EMP.EMPNO', NULL, 'Y', NULL)
/
INSERT INTO WF_ATTRIBUTES ( ID, PRCE_ID, DATA_TYPE, NAME, LENGTH, DESCRIPTION, INITIAL_VALUE, KEEP,
REPLICATION_TIMESTAMP ) VALUES ( 
20, 10, 'CHARACTER', 'APPROVED', 1, 'Is the request approved', NULL, 'N', NULL)
/
INSERT INTO WF_ATTRIBUTES ( ID, PRCE_ID, DATA_TYPE, NAME, LENGTH, DESCRIPTION, INITIAL_VALUE, KEEP,
REPLICATION_TIMESTAMP ) VALUES ( 
30, 10, 'CHARACTER', 'HAPPY', 1, 'Is the employee happy with the result?', NULL, 'N'
, NULL)
/

-- Add activities
 
INSERT INTO WF_TRANSITIONS ( ACTI_PRCE_ID_FROM, ACTI_ID_FROM, ACTI_PRCE_ID_TO, ACTI_ID_TO, NAME,
DESCRIPTION, CONDITION, CONDITION_TYPE, REPLICATION_TIMESTAMP ) VALUES ( 
10, 10, 10, 20, 'request to manager', 'request to manager', NULL, NULL, NULL)
/
INSERT INTO WF_TRANSITIONS ( ACTI_PRCE_ID_FROM, ACTI_ID_FROM, ACTI_PRCE_ID_TO, ACTI_ID_TO, NAME,
DESCRIPTION, CONDITION, CONDITION_TYPE, REPLICATION_TIMESTAMP ) VALUES ( 
10, 20, 10, 30, 'denied by manager', 'denied by manager', 'a.name=''APPROVED'' AND i.value <>''Y''', 'CONDITION'
, NULL)
/
INSERT INTO WF_TRANSITIONS ( ACTI_PRCE_ID_FROM, ACTI_ID_FROM, ACTI_PRCE_ID_TO, ACTI_ID_TO, NAME,
DESCRIPTION, CONDITION, CONDITION_TYPE, REPLICATION_TIMESTAMP ) VALUES ( 
10, 20, 10, 50, 'approved by manager', 'approved by manager', 'a.name=''APPROVED'' AND i.value =''Y''', 'CONDITION'
, NULL)
/
INSERT INTO WF_TRANSITIONS ( ACTI_PRCE_ID_FROM, ACTI_ID_FROM, ACTI_PRCE_ID_TO, ACTI_ID_TO, NAME,
DESCRIPTION, CONDITION, CONDITION_TYPE, REPLICATION_TIMESTAMP ) VALUES ( 
10, 30, 10, 40, 'not happe', 'employee is not happy', 'a.name=''HAPPY'' and i.value=''N''', 'CONDITION', NULL)
/
INSERT INTO WF_TRANSITIONS ( ACTI_PRCE_ID_FROM, ACTI_ID_FROM, ACTI_PRCE_ID_TO, ACTI_ID_TO, NAME,
DESCRIPTION, CONDITION, CONDITION_TYPE, REPLICATION_TIMESTAMP ) VALUES ( 
10, 40, 10, 50, 'request to president', 'request to president', NULL, NULL, NULL)
/
INSERT INTO WF_TRANSITIONS ( ACTI_PRCE_ID_FROM, ACTI_ID_FROM, ACTI_PRCE_ID_TO, ACTI_ID_TO, NAME,
DESCRIPTION, CONDITION, CONDITION_TYPE, REPLICATION_TIMESTAMP ) VALUES ( 
10, 50, 10, 60, 'result to employee', 'final result to employee', NULL, NULL, NULL)
/
INSERT INTO WF_TRANSITIONS ( ACTI_PRCE_ID_FROM, ACTI_ID_FROM, ACTI_PRCE_ID_TO, ACTI_ID_TO, NAME,
DESCRIPTION, CONDITION, CONDITION_TYPE, REPLICATION_TIMESTAMP ) VALUES ( 
10, 50, 10, 70, 'change paycheck', 'change paycheck', 'a.name=''APPROVED'' and i.value=''Y''', 'CONDITION'
, NULL)
/
 

COMMIT
/
QUIT
/
