set pagesi 1000 linesi 1000 trimspool on head on 
col propagation_name format a15
col source format a20
col destination format a32
select PROPAGATION_NAME, STATUS
--,SOURCE_QUEUE_OWNER||'.'||SOURCE_QUEUE_NAME SOURCE
--,DESTINATION_QUEUE_OWNER||'.'||DESTINATION_QUEUE_NAME||'@'||DESTINATION_DBLINK DESTINATION
,SOURCE_QUEUE_NAME SOURCE
,DESTINATION_QUEUE_NAME||'@'||DESTINATION_DBLINK DESTINATION
from DBA_PROPAGATION
order by PROPAGATION_NAME
/
